name: Build Docker and Upload to Release

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        hbuilderx:
          - version: 5.0.2026013113-alpha
            url: https://download1.dcloud.net.cn/download/HBuilderX.5.0.2026013113-alpha.linux_x64.full.tar.gz
        slim:
          - true
          - false

    name: Build HBuilderX Docker Image (${{ matrix.hbuilderx.version }}${{ matrix.slim && '-slim' || '' }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache HBuilderX tgz
        id: cache-hbuilderx
        uses: actions/cache@v4
        with:
          key: hbuilderx-${{ matrix.hbuilderx.version }}
          path: ./.cache/hbuilderx

      - name: Download HBuilderX ${{ matrix.hbuilderx.version }}
        if: steps.cache-hbuilderx.outputs.cache-hit != 'true'
        run: |
          wget -O ./hbuilderx.tar.gz https://download1.dcloud.net.cn/download/HBuilderX.${{ matrix.hbuilderx.version }}.linux_x64.full.tar.gz
          mkdir -p ./.cache/hbuilderx
          tar -xzf hbuilderx.tar.gz -C ./.cache/hbuilderx --strip-components=1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for HBuilderX ${{ matrix.hbuilderx.version }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t hbuilderx:${{ matrix.hbuilderx.version }} \
            --build-arg HBUILDERX_PATH=./.cache/hbuilderx \
            --build-arg SLIM=${{ matrix.slim }} \
            --output type=docker,dest=./hbuilderx.${{ matrix.hbuilderx.version }}${{ matrix.slim && '-slim' || '' }}.tar .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hbuilderx.${{ matrix.hbuilderx.version }}${{ matrix.slim && '-slim' || '' }}.tar.zip
          path: ./hbuilderx.${{ matrix.hbuilderx.version }}${{ matrix.slim && '-slim' || '' }}.tar

  release:
    needs: build
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download built image
        uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./hbuilderx.*.tar
          prerelease: ${{ contains(matrix.hbuilderx.version, '-alpha') }}
          name: v${{ matrix.hbuilderx.version }}
          tag_name: v${{ matrix.hbuilderx.version }}
          body: |
            ## HBuilderX Docker Images

            This release contains Docker images for HBuilderX.

            - hbuilderx.<version>.tar: Docker image for HBuilderX Stable version
            - hbuilderx.<version>-slim.tar: Slim Docker image for HBuilderX Stable version
            - hbuilderx.<version>-alpha.tar: Docker image for HBuilderX Alpha version
            - hbuilderx.<version>-alpha-slim.tar: Slim Docker image for HBuilderX Alpha version

            ### Usage

            To load the Docker image, use the following command:

            ```bash
            docker load -i hbuilderx.<version>.tar
            ```

            After loading the image, you can run the container using:
            
            ```bash
            docker run -it hbuilderx:<tag>
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
